[variables]
NIXPACKS_NO_CACHE = "1"
PIP_NO_CACHE_DIR = "1"

[phases.setup]
nixPkgs = ["python311"]

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --max-requests 1000 --max-requests-jitter 50"
